### ISSUE TITLE
forbidden 403 login

### ISSUE THREAD

**Issue by reto88** [Tob1asDocker/minio#1]
Hi, I use your dockerimage with a raspberry pi and try to connect over ssl. 
I did it with this manual https://docs.min.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio.html
the login page is working over ssl, but when i want do login, then I get a 403 forbidden error back. Do you have any idea why?

Best
Reto

**Comment by Tob1as** [comment]
Hi,

i test it with this settings:

```yaml
version: "2.4"
services:
  minio:
    image: tobi312/minio:latest
    container_name: minio
    #restart: unless-stopped
    ports:
      - "9000:9000" # MinIO Buckets API
      - "9001:9001" # MinIO Console
    volumes:
      - ./minio-data:/data:rw
      - ./ssl/ssl.crt:/root/.minio/certs/public.crt:ro
      - ./ssl/ssl.key:/root/.minio/certs/private.key:ro
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      # https://github.com/minio/minio#things-to-consider
      MINIO_SERVER_URL: "https://minio.example.net:9000"
      MINIO_BROWSER_REDIRECT_URL: "https://minio.example.net:9001"
    command:  ["server", "--address", ":9000", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "--insecure", "https://localhost:9000/minio/health/live"]
      start_period: 15s
      interval: 60s
      timeout: 10s
      retries: 3
```
and a self sign cert (in subfolder ./ssl):
```sh
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout example.key -out example.crt -subj '/CN=example.net' \
  -addext 'subjectAltName=DNS:example.net,DNS:minio.example.net'
```
the browser login https://minio.example.net:9001 should work.

(replace minio.example.com with some hostname or domain)
